set(__QT_DEPLOY_TARGET_soem_FILE D:/QtProjects/DynamicxEcatTool-codex/SOEM/soem.lib)
set(__QT_DEPLOY_TARGET_soem_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_soem_interface_FILE D:/QtProjects/DynamicxEcatTool-codex/SOEM_interface/soem_interface.dll)
set(__QT_DEPLOY_TARGET_soem_interface_TYPE SHARED_LIBRARY)
set(__QT_DEPLOY_TARGET_soem_interface_RUNTIME_DLLS )
set(__QT_DEPLOY_TARGET_dynamicx_backend_FILE D:/QtProjects/DynamicxEcatTool-codex/dynamicx_backend.lib)
set(__QT_DEPLOY_TARGET_dynamicx_backend_TYPE STATIC_LIBRARY)
set(__QT_DEPLOY_TARGET_DynamicxEcatTool_FILE D:/QtProjects/DynamicxEcatTool-codex/DynamicxEcatTool.exe)
set(__QT_DEPLOY_TARGET_DynamicxEcatTool_TYPE EXECUTABLE)
set(__QT_DEPLOY_TARGET_DynamicxEcatTool_RUNTIME_DLLS D:/Qt/6.8.3/msvc2022_64/bin/Qt6QuickControls2.dll;D:/Qt/6.8.3/msvc2022_64/bin/Qt6QuickTemplates2.dll;D:/Qt/6.8.3/msvc2022_64/bin/Qt6Quick.dll;D:/Qt/6.8.3/msvc2022_64/bin/Qt6QmlMeta.dll;D:/Qt/6.8.3/msvc2022_64/bin/Qt6QmlWorkerScript.dll;D:/Qt/6.8.3/msvc2022_64/bin/Qt6OpenGL.dll;D:/Qt/6.8.3/msvc2022_64/bin/Qt6Gui.dll;D:/Qt/6.8.3/msvc2022_64/bin/Qt6QmlModels.dll;D:/Qt/6.8.3/msvc2022_64/bin/Qt6Qml.dll;D:/Qt/6.8.3/msvc2022_64/bin/Qt6Network.dll;D:/Qt/6.8.3/msvc2022_64/bin/Qt6Core.dll;D:/Program Files/vcpkg/installed/x64-windows/bin/yaml-cpp.dll;D:/QtProjects/DynamicxEcatTool-codex/SOEM_interface/soem_interface.dll)
